name: Check
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup | Node
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - name: Run | Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup | Node
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - name: Run | Format
        run: pnpm format:check
