name: Check
on:
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - run: tsc
          - run: eslint
          - run: prettier
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Node
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - name: Run | ${{ matrix.run }}
        run: pnpm lint:${{ matrix.run }}
