name: Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Node
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - name: Setup | GitHub Pages
        id: config
        uses: actions/configure-pages@v4

      - name: Build | Build
        run: pnpm build
        env:
          NODE_ENV: production
          BASE_PATH: ${{ steps.config.outputs.base_path }}

      - name: Deploy | Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy | GitHub Pages
        uses: actions/deploy-pages@v2
